config:
  selfUrl: # https://erp-st-basket
  corsOrigins: # https://erp-st-gateway-web,https://erp-st-gateway-public-web,https://erp-st-public
  connectionStrings:
    administrationService: #
  authServer:
    authority: http://erp-st-authserver
    requireHttpsMetadata: "false"
    metadataAddress: http://erp-st-keycloak:8080
    swaggerClientId: "WebGateway_Swagger"
  dotnetEnv: Staging
  redisHost: erp-st-redis
  rabbitmqHost: erp-st-rabbitmq
  elasticsearchHost: erp-st-elasticsearch
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  remoteServices:
    catalogBaseUrl: #
    catalogGrpcUrl: #

ingress:
  host: erp-st-basket
  tlsSecret: erp-wildcard-tls

image:
  repository: walsunerp/service-basket
  tag: latest
  pullPolicy: IfNotPresent

env: {}
    