config:
  selfUrl: https://erp-st-public-web
  gatewayUrl: https://erp-st-gateway-web-public
  authServer:
    authority: http://erp-st-authserver
    requireHttpsMetadata: "false"
    isOnProd: false
    metaAddress: #
  dotnetEnv: Staging
  redisHost: erp-st-redis
  rabbitmqHost: erp-st-rabbitmq
  elasticsearchHost: erp-st-elasticsearch
  stringEncryptionDefaultPassPhrase: yAGSYC55gxT6p7dX
  

ingress:
  host: erp-st-public-web
  tlsSecret: erp-wildcard-tls

image:
  repository: walsunerp/app-publicweb
  tag: latest
  pullPolicy: IfNotPresent

env: {}
