FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY Walsun.Erp ./Walsun.Erp
WORKDIR /src/Walsun.Erp/services/administration/src/Walsun.Erp.AdministrationService.HttpApi.Host
RUN dotnet publish -c Release -o bin/Release/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0  AS final
WORKDIR /app
COPY --from=build /src/Walsun.Erp/services/administration/src/Walsun.Erp.AdministrationService.HttpApi.Host/bin/Release/publish/ .
ENTRYPOINT ["dotnet", "Walsun.Erp.AdministrationService.HttpApi.Host.dll"]