FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY Walsun.Erp ./Walsun.Erp
WORKDIR /src/Walsun.Erp/apps/public-web/src/Walsun.Erp.PublicWeb
RUN dotnet publish -c Release -o bin/Release/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0  AS final
WORKDIR /app
COPY --from=build /src/Walsun.Erp/apps/public-web/src/Walsun.Erp.PublicWeb/bin/Release/publish/ .
ENTRYPOINT ["dotnet", "Walsun.Erp.PublicWeb.dll"]