config:
  kcDb: postgres
  kcDbUrl: jdbc:postgresql://erp-st-postgresdb:5432/keycloak
  kcDbUrlHost: erp-st-postgresdb
  kcDbUrlPort: 5432
  kcDbUrlDatabase: keycloak
  kcDbUsername: postgres
  kcDbPassword: myPassw0rd
  keycloakAdmin: admin
  keycloakAdminPassword: 1q2w3E*
  kcHealthEnabled: true
  kcHttpRelativePath : /
  kcProxy: edge
  proxyAddressForwarding: true
  kcHttpEnabled: true
  kcHostnameUrl: https://account.walsunerp.dev
  kcHostnameAdminUrl: https://account.walsunerp.dev
  jgroupsDnsQuery: erp-st-keycloak

ingress:
  host: account.walsunerp.dev
  tlsSecret: erp-wildcard-tls

image:
  repository: quay.io/keycloak/keycloak
  tag: 21.1.1
  pullPolicy: IfNotPresent

# command:
#     - "/opt/keycloak/bin/kc.sh"
#     - "start"
#     - "--auto-build"
#     - "--http-enabled=true"
#     - "--http-port=8080"
#     - "--hostname-strict=false"
#     - "--hostname-strict-https=false"

env: {}