config:
  selfUrl: # https://erp-st-payment
  corsOrigins: # https://erp-st-gateway-web,https://erp-st-gateway-public-web
  connectionStrings:
    paymentService: #
    administrationService: #
  authServer:
    authority: http://erp-st-authserver
    requireHttpsMetadata: "false"
    metadataAddress: http://erp-st-keycloak:8080
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging
  redisHost: erp-st-redis
  rabbitmqHost: erp-st-rabbitmq
  elasticsearchHost: erp-st-elasticsearch
  stringEncryptionDefaultPassPhrase: yAGSYC55gxT6p7dX

ingress:
  host: erp-st-payment
  tlsSecret: erp-wildcard-tls

image:
  repository: walsunerp/service-payment
  tag: latest
  pullPolicy: IfNotPresent

env: {}
    