config:
  selfUrl: # https://erp-st-cmskit
  corsOrigins: # https://erp-st-gateway-web,https://erp-st-gateway-public-web
  connectionStrings:
    cmskitService: #
    administrationService: #
  authServer:
    authority: http://erp-st-authserver
    requireHttpsMetadata: "false"
    metadataAddress: http://erp-st-keycloak:8080
    swaggerClientId: WebGateway_Swagger
  remoteServices:
    abpIdentityBaseUrl: #
  dotnetEnv: Staging
  redisHost: erp-st-redis
  rabbitmqHost: erp-st-rabbitmq
  elasticsearchHost: erp-st-elasticsearch
  stringEncryptionDefaultPassPhrase: yAGSYC55gxT6p7dX

synchedCommunication:
  grantType: # "client_credentials"
  clientId: # 
  clientSecret: #
  authority: # "https://erp-st-authserver"
  scope: # "IdentityService"

ingress:
  host: erp-st-cmskit
  tlsSecret: erp-wildcard-tls

image:
  repository: walsunerp/service-cmskit
  tag: latest
  pullPolicy: IfNotPresent

env: {}
    